%This code is meant to use time periods delineated by signal pulses to
%separate out chunks of spike times. This will save these spike files in
%the masterStruct file.

function [masterStruct] = functionPairingSpikeSeparator(masterStruct,...
   truncatedNames,spikeNames,names);
%First, I want to pull all the time periods.
timesBaseline = masterStruct.TimePeriods.Baseline;
timesTuningFirst = masterStruct.TimePeriods.(names{1});
timesPresentationFirst = masterStruct.TimePeriods.(names{3});
timesPairing = masterStruct.TimePeriods.(names{5});
timesPresentationSecond = masterStruct.TimePeriods.(names{4});
timesTuningSecond = masterStruct.TimePeriods.(names{2});

%stores spikes as separated spike times. 
for i = 1:size(truncatedNames,2);
    for j = 1:masterStruct.(truncatedNames{i}).Clusters
        masterStruct.(truncatedNames{i}).BaselineSpikes{j} = ...
            masterStruct.(truncatedNames{i}).SpikeTimes{j}(...
            masterStruct.(truncatedNames{i}).SpikeTimes{j}>timesBaseline(1) &...
            masterStruct.(truncatedNames{i}).SpikeTimes{j}<timesBaseline(2));
        masterStruct.(truncatedNames{i}).(spikeNames{1}){j} = ...
            masterStruct.(truncatedNames{i}).SpikeTimes{j}(...
            masterStruct.(truncatedNames{i}).SpikeTimes{j}>timesTuningFirst(1) &...
            masterStruct.(truncatedNames{i}).SpikeTimes{j}<timesTuningFirst(2));
        masterStruct.(truncatedNames{i}).(spikeNames{2}){j} = ...
            masterStruct.(truncatedNames{i}).SpikeTimes{j}(...
            masterStruct.(truncatedNames{i}).SpikeTimes{j}>timesTuningSecond(1) &...
            masterStruct.(truncatedNames{i}).SpikeTimes{j}<timesTuningSecond(2));
        masterStruct.(truncatedNames{i}).(spikeNames{3}){j} = ...
            masterStruct.(truncatedNames{i}).SpikeTimes{j}(...
            masterStruct.(truncatedNames{i}).SpikeTimes{j}>timesPresentationFirst(1) &...
            masterStruct.(truncatedNames{i}).SpikeTimes{j}<timesPresentationFirst(2));
        masterStruct.(truncatedNames{i}).(spikeNames{4}){j} = ...
            masterStruct.(truncatedNames{i}).SpikeTimes{j}(...
            masterStruct.(truncatedNames{i}).SpikeTimes{j}>timesPresentationSecond(1) &...
            masterStruct.(truncatedNames{i}).SpikeTimes{j}<timesPresentationSecond(2));
        masterStruct.(truncatedNames{i}).(spikeNames{5}){j} = ...
            masterStruct.(truncatedNames{i}).SpikeTimes{j}(...
            masterStruct.(truncatedNames{i}).SpikeTimes{j}>timesPairing(1) &...
            masterStruct.(truncatedNames{i}).SpikeTimes{j}<timesPairing(2));
    end
end


end
